### ISSUE TITLE
refactor/registerUser

### ISSUE THREAD

**Issue by scarlosro** [Solify-IT/psyche-ing#43]
¿Qué hace esté PR?

1. Se corrige defectos, por lo cual se añade: Encriptación de contraseñas
2. Se añade el método al iniciar sesión
3. Se verifica que la contraseña coincida al momento.

¿Cómo debería ser probado manualmente?
Ingresar a http://localhost:3000/#/registerUser

¿Algún background que desees proveer?

1. Falta añadir la validación correcta en el front del username y correo para que muestre el error de manera explicita.
2. Hay que correr el comando yarn Install para instalar las nuevas dependencias (bcrypt)
3. Hay un fix del diseño que se implemento después de que yo hiciera esta rama, por lo cual, el diseño no coincide pero al hacer el merge se corrige.

<img width="1440" alt="Captura de Pantalla 2021-05-18 a la(s) 22 35 05" src="https://user-images.githubusercontent.com/33816613/118752758-4e31f980-b829-11eb-9c4d-a57d3208f2f0.png">

**Comment by albertcastaned** [comment]
Esto es un issue, no un PR 💩

**Comment by scarlosro** [comment]
JAJAJAJ
