### ISSUE TITLE
Pruebas Unitarias

### ISSUE THREAD

**Issue by scarlosro** [Solify-IT/psyche-ing#66]
# Pruebas Unitarias

## Introducción

Al desarrollar un software debemos garantizar que el sistema cumple con los estándares de calidad necesarios y que el sistema funcione de manera correcta ante cualquier situación; es por esto, que es necesario la introducción de desarrollo de pruebas en este caso unitarias, para verificar que en cualquier situación que se pueda presentar el sistema sea capaz de reaccionar de manera apropiada.

## Pruebas Unitarias

Las pruebas unitarias o también conocido como unit testing son una forma de comprobar que un fragmento de código funcione correctamente, es decir, el código hace lo que tiene que hacer.

Para poder probar nuestros códigos utilizamos el siguiente framework **jest**, el cual nos permite realizar estas pruebas unitarias.

## Utilizando Jest

En nuestro proyecto, tanto en el back-end como el front-end tenemos la carpeta de test para el caso del back-end podemos probar:

1. Interactor
2. Presenter 
3. Repository

Esto, procede a que utilizamos a clean architecture y es lo mismo que se busca en los test, que a continuación se detallan.
### Interactor
Para la parte del Interactor utilizamos principalmente las funciones Mock, prácticamente está parte consiste en actuar como un "espía" y mandar a llamar una función de manera indirecta.

Como podemos seguir en el siguiente ejemplo, pretendemos cachar el error del Repositorio de usuarios (userRepository) y cuál es el método que deseamos probar, para cumplir está parte de probar cierto fragmento de código. Una vez determinado estas partes, procedemos a hacer la "implementación" de ese método. Para esté caso, fingimos el throw new Error.
 
En la siguiente línea de const donde mandamos a ejecutar la función registerDoctorProfile, para finalmente utilizar expect, la cual revisamos si es que lo que esperábamos es igual a lo que realmente paso, como vemos esperamos un error y posteriormente esperamos que realmente sea un Nulo, ya que como se comento anteriormente este test se implementa como un espía.

 <img width="875" alt="Captura de Pantalla 2021-05-30 a la(s) 21 39 40" src="https://user-images.githubusercontent.com/33816613/120132208-8c1b1000-c18f-11eb-880b-d9cfcc5f727f.png">

### Repository

En la carpeta de test/repository probamos principalmente la funcionalidad con la conexión a la base de datos, en la cual, esperamos que actúe de manera correcta y recibir ciertos resultados, por ejemplo, si queremos consultar algún registro que existe, esperaríamos que lo regrese de manera exitosa.

Como podemos ver el siguiente ejemplo, esperamos que nos generé un error puesto que el dato no existe, para esto, generamos la conexión con la base de datos, continuamos a llamar la función que vamos a evaluar, y como vemos, queremos encontrar el expediente con folio 99. Finalmente, validamos que recibamos los resultados deseados, que existe un error, es decir se definió y que el resultado sea nulo, pues como mencionamos, ese registro no existe realmente en nuestra base de datos.

<img width="560" alt="Captura de Pantalla 2021-05-31 a la(s) 22 18 10" src="https://user-images.githubusercontent.com/33816613/120261715-17fb6d80-c25e-11eb-8a27-83f1398e58e0.png">

### Presenter

Al igual que los anteriores, este se ubica en test/presenter y es capaz de revisar que las llamadas a los métodos están respondiendo de manera adecuada y que por ende recibamos los datos solicitados ya pasados de la base de datos, por lo cual, esperamos tenga la estructura de la base de datos de un expediente.

En este caso, como podemos observar, deberíamos recibir el detalle del expediente cuando llamamos el método 
<img width="525" alt="Captura de Pantalla 2021-05-31 a la(s) 22 29 21" src="https://user-images.githubusercontent.com/33816613/120262633-a7555080-c25f-11eb-870f-8133c8966a03.png">

**Comment by scarlosro** [comment]
Pndte aún...

**Comment by albertcastaned** [comment]
Va bien. Podrías mencionar que se utiliza Clean Architecture en este caso.
